language: python
sudo: required
os:
  - linux
# only linux supports the python versions we do
#  - osx
#  - windows
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
before_install:
  - pip install flake8
install:
  - pip install .
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script: flake8 --max-line-length 120
script: pytest