language: python
sudo: required
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
before_install:
  - pip install flake8
install:
  - pip install .
stages:
  - lint
  - test
jobs:
  include:
    - stage: lint
      script: flake8 --max-line-length 120
script: pytest