language: python
os:
- linux
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
before_install:
- pip install flake8
install:
- pip install .
stages:
- lint
- test
jobs:
  include:
  - stage: lint
    script: flake8 --max-line-length 120
script: pytest
deploy:
  provider: pypi
  user: __token__
  password:
    secure: qiO7oDmkRH7IH9fFoVdX5fQTJWdntKjOOCAhQKuwwlTb5MMthWU0QSGvu1gJ9RqkavTJARrnwy6FA+rEks50QCHMcqCN/tS4Q0GSyiSE4Fpar7Adr6XFntJuoo3i866yEuiSo+WhQBlcLCk0ARpL9t5jh5AJEXQwKbQTrprWQhZnxKbfY9Nd6m/upKJoXI/v+oj/jtH488Q00UyEH/EdTygBlidbIv472uOdWFFb8oN1EnoKf4ShSNqmt+zt5J5YxFhZu60k6n4VVKXNCSK/xI/JFt/L8j3Rm+rv05J+B/whkhiWXtmyT5xi+dPD4sYPDIWGxVMmN9hOyhgq7P2F+PvAuxFvNUlHvbwXqQQGUoj9j2UsVwqnP2wxVndfs5ENAipuwKthyzNKhjZhpHWlxQOVmBr3buVWwERKMmX1R7YoKdTQ8HpiXpERXvYZBKbGel4AtypddNSD8JIPnf5Wqmmce3AULuMaUAC71qQKAOz8CI7K+wdj/B+WwlHsa+yYsJBv4uy3pDLvd76C6pPz9yKoKBwJ5XLLTVfOtInMUqqeB0VlawAYqQRbaGcffJOQFvKEvOrUCoRQRBoVOrhRX+rRHE1fAVSfoS1gXOhoEUYHX4WsHIXV/ppe1bA9vm1pYGj489ro0uQQbY7BAL9xctMnirtLHl0dN/YIQ58oiMQ=
  on:
    tags: true
  skip_existing: true
